### PR TITLE
ContainerTest implemented for branch 3.5. Hope you will check :)

### PR DESCRIPTION
**Pull request by baktify**
Hello Gio. I implemented ContainerTest for custom DI Container class. I'd be so happy if you'd check it out :)

### CODE REVIEW

**Comment by baktify** [comment]
By the way, at the beginning, I wrote the tests on my own repository that wasn't forked from your repository. In order to be able to make pull request, I forked your repo and moved my tests there.

**Comment by ggelashvili** [comment]
Looks good, good job. Not going to merge it since there are changes related to compose files & want to avoid confusion. Good job!

**Comment by baktify** [comment]
> Looks good, good job. Not going to merge it since there are changes related to compose files & want to avoid confusion. Good job!

That's absolutely fine if you don't merge. Thanks for checking. Do you have any recommendations? Is there anything that can be improved?

**Comment by ggelashvili** [comment]
It looks fine at a quick glance. The container class itself is pretty minimal & you are doing a good job at covering different scenarios.

**Pull request closed without merging**
